### ISSUE TITLE
Diseño cambios

### ISSUE THREAD

**Issue by Fernandoramas** [anderjs/aptis-platform#101]
Esto son criticas constructivas. Solo son bocetos que tu debes de darle la forma y perfeccionarlo. Tómalo como ideas.
<img width="1256" alt="Captura de pantalla 2019-09-17 a las 17 55 38" src="https://user-images.githubusercontent.com/39381886/65143907-63340500-da16-11e9-82ef-7b156f1d000c.png">
/login:
1. [x] Intentar copiar el estilo de la imagen adjunta.
2. [x] Cambiar ingresar por acceder. 
3. [x] En el botón de google añadir "entra con: //logo de google"
4. [x] Cambiar el icono de carga.

<img width="1213" alt="Captura de pantalla 2019-09-18 a las 13 14 44" src="https://user-images.githubusercontent.com/39381886/65143924-6c24d680-da16-11e9-90a1-3b7597d8b2c7.png">
/Dashboard:

1. [x]  Añadir el logo con AptisGo en letra en la esquina superior izquierda (en la barra)
2. [x] Añadir el nombre de usuario y apellido junto a su foto de perfil a la derecha (en la barra)
3. [x] Intentar seguir el estilo de la imagen. Más minimalista. Una vez lo tienes, añadir iconos con color y que sean los iconos los que hagan del gráfico algo atractivo. (Revisar duolingo)
4. [x] Hacer más grande el box de Exámenes (el doble).
5. [x] Cambiar el icono de los detalles del examen (Modal)

/Ejercicios: 
1. [x] Ampliar la letra y oscurecerla. 
2. [x] Las instrucciones en negrita y más grande que el tamaño del texto.
3. [x] Aumentar el width de los box del dropdown, (para que se entienda que tiene que seleccionar ahi) Al tamaño de una palabra o más.

**Comment by anderjs** [comment]
@ItsMeAndrea

**Comment by Fernandoramas** [comment]
![image](https://user-images.githubusercontent.com/39381886/65267690-d7090700-db15-11e9-90cc-e06111794644.png)
/signup:

- [ ] 1. Añadir el mismo boton de google de /login.
- [ ] 2. Aplicar el mismo diseño del background y las letras de AptisGo.

**Comment by anderjs** [comment]
@ItsMeAndrea
